### ISSUE TITLE
new version 0.5.4 is bugged, dont generate output files, seems that it doesnt download resorces either...

### ISSUE THREAD

**Issue by sonkite225** [chidiwilliams/buzz#152]
new version 0.5.4 is bugged, dont generate output files, seems that it doesnt download resorces either...

the last version 0.5.3 has perfectly worked, its only a prob of the new one

(first installed the new over the old version, after i saw that the eroor occures i deinstalled buzz and installed the new fresh. but changed nothing. still same error)

PS: windows

**Comment by sonkite225** [comment]
update:

old resources in .cache\whisper deleted, now loading of new ones works. ok

but generating output files is buggy, sometimes an output file is generated, sometimes not.

**Comment by sonkite225** [comment]
and "if" an output file is generated, sometimes its correct, sometimes its an empty file...

**Comment by chidiwilliams** [comment]
That's really weird. Are you on Mac/Windows?

**Comment by sonkite225** [comment]
windows.

especially the high profile causes problems.
try just a test mp3 (which mi the last version always! worked fine) bereis the 4th or 5th time. 
no output file. in the log it looks the same as if everything had worked, there is absolutely nothing apparent.

and as I said also the other 3 profiles, sometimes it works and it comes out a file (which is sometimes ok sometimes empty)
or it comes also none at all out.

the old version also tested again, which works without problems. the problems are exclusively in the 0.5.4

Translated with www.DeepL.com/Translator (free version)

**Comment by sonkite225** [comment]
nach dem 8. versuch im high profil kam endlich überhaupt eine datei raus ^^
diese war leer.
der 9. versuch gab dann wieder eine aus, diesmal war sie in ordnung...

absolut seltsam

**Comment by chidiwilliams** [comment]
Could you try this build: https://github.com/chidiwilliams/buzz/suites/9247184069/artifacts/432520528?

**Comment by sonkite225** [comment]
yess :) this build works perfect :)
tried all4 profiles, every single one worked first try great :)

is it wanted that the generated file opens itself after generating? (but also does not bother ^^)

may i ask what the problem was? was really a strange behavior ^^

**Comment by sonkite225** [comment]
ach, und wo ich grad dabei bin noch eine frage.
ich denke du nutzt pyinstaller (onedir) um eine exe zu genereieren oder ?!?

aber was mich interessieren würde, womit erstellst du aus dem (one)dir den installer in form einer einzelnen exe. gibts dafür ein spezielles programm? :)

**Comment by chidiwilliams** [comment]
- Great. Glad to hear it works fine.
- Yes, I thought it might be a good idea to open the file after generation so it's easy to find and use immediately. But I'm happy to take feedback/add an option to disable if it's not useful
- The problem was on [this line](https://github.com/chidiwilliams/buzz/pull/153/files#diff-3cbc0fcda69a9da6e615e2a4fe21b03f8ea6face1a58f166387467d0b0ac6762L523). Basically, I had some code that cleaned up the transcription process and I was calling it after the transcription ends but before the file gets written. So sometimes, the file will get written before the clean up finishes, and other times the clean up will finish first and stop the file from getting written. I moved the clean up code to run after the file gets written.
- I use [InnoSetup](https://jrsoftware.org/isinfo.php) to create the .EXE from the PyInstaller files. You can find the config [here](https://github.com/chidiwilliams/buzz/blob/main/installer.iss) and [here](https://github.com/chidiwilliams/buzz/blob/main/Makefile#L14).

**Comment by sonkite225** [comment]
ah, ok, that explains it ^^ but good that the fix for it was an easy one ^^
