### ISSUE TITLE
failed to execute script due to unhandled exception : 'utf-8' codec can't decode byte 0xc2

### ISSUE THREAD

**Issue by ydwg** [chidiwilliams/buzz#180]
![20221124123749](https://user-images.githubusercontent.com/29204939/203695785-1ecd7bed-a270-4a1a-a270-3d5cacbf59da.png)

**Comment by flottant** [comment]
The same problem. Any possible solution or the latest edition fixed it ?

**Comment by chidiwilliams** [comment]
Hi, yes, this seems to be happening because the names of your audio devices are not in UTF-8. I'm not sure what the correct fix should be, but a workaround is to turn on "Beta: Use Unicode UTF-8" in your Region settings. See:

- https://github.com/chidiwilliams/buzz/issues/230
- https://github.com/jaakkopasanen/Impulcifer/issues/53

![image](https://user-images.githubusercontent.com/17879672/206969572-404dd91a-7bf3-4734-b3d7-e8e781429215.png)

**Comment by Andrea-lyz** [comment]
> Hi, yes, this seems to be happening because the names of your audio devices are not in UTF-8. I'm not sure what the correct fix should be, but a workaround is to turn on "Beta: Use Unicode UTF-8" in your Region settings. See:
> 
> * [Bug: Can't open buzz.exe on my windows 10 #230](https://github.com/chidiwilliams/buzz/issues/230)
> * [The error occurred while running recorder jaakkopasanen/Impulcifer#53](https://github.com/jaakkopasanen/Impulcifer/issues/53)
> 
> ![image](https://user-images.githubusercontent.com/17879672/206969572-404dd91a-7bf3-4734-b3d7-e8e781429215.png)

Hi, enabling Unicode UTF-8 does run Buzz properly, but it causes some Chinese characters in some software to be garbled or even run incorrectly, I have to turn off Unicode UTF-8 again, is there another way to fix it? I see you say it's because of the audi
![屏幕截图 2022-12-16 191343](https://user-images.githubusercontent.com/52863141/208162612-eda57247-6bc8-49f0-a4f6-ea68157f2fe5.png)
o device name? How do I change it?My change to English in the red √ does not seem to do anything.
