### ISSUE TITLE
0.7.2 (and lower) whisper cpp dont work

### ISSUE THREAD

**Issue by sonkite225** [chidiwilliams/buzz#372]
dont know why, model downloads correctly, but every transcript instant jumps from qeued tu finished but produce only emtyness...

**Comment by sonkite225** [comment]
ps: whisper withot coo works without probs

**Comment by Huansock** [comment]
me too (m1 mac air)

**Comment by fqx** [comment]
same here, MacBook Pro with intel cpu

**Comment by chidiwilliams** [comment]
This is a known problem which I've mentioned in some other open issues, due to Mac's updates to its security settings. I don't think it's fixable until there's a new version of PyInstaller that addresses the problem. That said, I've been working on a better, native version of Buzz. It should be available on the App Store soon (although it would likely have a small one-time price). If you would like to be added to the TestFlight, there's a link here: https://github.com/chidiwilliams/buzz/discussions/374. Thanks.

**Comment by sonkite225** [comment]
for me is not on mac, its on win10 btw

**Comment by Durden-T** [comment]
win10 same problem
