### ISSUE TITLE
When you release new version for windows?

### ISSUE THREAD

**Issue by johnfelipe** [chidiwilliams/buzz#630]

**Comment by chidiwilliams** [comment]
Still testing out in the new large model, but should be out in a few days

**Comment by johnfelipe** [comment]
@chidiwilliams pls add new release

https://github.com/openai/whisper/releases/tag/v20231117

**Comment by cproof** [comment]
+1, looking forward to a new release containing the #636 fix, as the Actions build doesn't seem to work unfortunately

![grafik](https://github.com/chidiwilliams/buzz/assets/4948782/097dbd89-fd6b-495e-9433-289a06afdbff)

**Comment by cproof** [comment]
Thank you, the error message is now fixed in the latest version. However, I'm getting a "System is unable to find the specified file" error message. (which is displayed after the ffmpeg conversion took place)

![grafik](https://github.com/chidiwilliams/buzz/assets/4948782/48fe8e37-0524-4aa1-b9a4-95b8a047f85b)

**Comment by PeggyFree** [comment]
Hello, I'm also voting for a windows .exe release

**Comment by cproof** [comment]
Just echoing that `v0.9.0` works quite well on windows (we've taken the artifact from the CI build: https://github.com/chidiwilliams/buzz/actions/runs/8300499527). Would welcome an official .exe

**Comment by raivisdejus** [comment]
All official app versions are attached to their releases https://github.com/chidiwilliams/buzz/releases
