### ISSUE TITLE
Adding transcription for output devices

### ISSUE THREAD

**Issue by agustinFeijoo** [chidiwilliams/buzz#717]
Hello, I think a trascription for output devices would be great.
In my company we are about to spend 800 USD just to transcribe one-to-one interviews hiring google workspace.
If this software would accept filter for output devices this would be a far better app because it's LOCAL, but currently it is not useful because I cant take the output devices and create a file that differentiate mic from speakers/headset. ( or even add two different devices)
Thanks, I appreciate your work

**Comment by raivisdejus** [comment]
@agustinFeijoo Please see updated FAQ section on notes how to get transcription from non-microphones https://chidiwilliams.github.io/buzz/docs/faq

Audio device routing is quite complex to implement for multiple operating systems due to their specifics, I have not found a solution that works stable and reliably, so for time being I see that bet solution is to do the routing on OS level and create virtual input device that you can hook up to the current recording mechanism in Buzz.

If anybody can recommend a solution that does this on code level, it could be implemented.
