### ISSUE TITLE
Buzz CLI does not close the GUI interface when task is done and it does not kill the command line CLI process either

### ISSUE THREAD

**Issue by jitendra-koodo** [chidiwilliams/buzz#993]
Tested in Git Bash 
Command :
"D:\Buzz\Buzz.exe" add -s large -l hi --srt  audio.wav

It generates the output but GUI interface is never clsoed and CLI on git bash remain open as well.

**Comment by raivisdejus** [comment]
@jitendra-koodo Thanks for you bug report. This will be fixed in next release.

You can test this in the latest development build:
1. Go to the build section https://github.com/chidiwilliams/buzz/actions/workflows/ci.yml?query=branch%3Amain
2. Click on the link to the latest build
3. Scroll down to the artifacts section in the build page
4. Download the installation files. Please note that you need to be logged in the Github to see the download links.

**Comment by raivisdejus** [comment]
@jitendra-koodo Added option to hide the GUI with `--hide-gui` option.
